#
#                           VELOXCHEM 1.0-RC
#         ----------------------------------------------------
#                     An Electronic Structure Code
#
#  Copyright © 2018-2021 by VeloxChem developers. All rights reserved.
#  Contact: https://veloxchem.org/contact
#
#  SPDX-License-Identifier: LGPL-3.0-or-later
#
#  This file is part of VeloxChem.
#
#  VeloxChem is free software: you can redistribute it and/or modify it under
#  the terms of the GNU Lesser General Public License as published by the Free
#  Software Foundation, either version 3 of the License, or (at your option)
#  any later version.
#
#  VeloxChem is distributed in the hope that it will be useful, but WITHOUT
#  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#  FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
#  License for more details.
#
#  You should have received a copy of the GNU Lesser General Public License
#  along with VeloxChem. If not, see <https://www.gnu.org/licenses/>.

stages:
  - build
  - test

.monkey:setup:
  tags:
    - vlx-test
  variables:
    OMP_NUM_THREADS: "6"
    GTESTROOT: "/home/xinli/software/googletest/googletest"
    MPICC: "$I_MPI_ROOT/intel64/mpi/mpiicc"
  before_script:
    - set +e && source /opt/intel/bin/compilervars.sh intel64 && set -e
    - export PATH=/opt/intel/intelpython3/bin:$PATH
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/intel/intelpython3/lib
    - python3 -m pip install --upgrade --user pip

monkey:build:
  extends: .monkey:setup
  stage: build
  script:
    - python3 config/generate_setup.py
    - make -j 6 -C src release
    - make -j 6 -C unit_tests release
  artifacts:
    paths:
      - build
    expire_in: 2 hours

monkey:pip_install:
  extends: .monkey:setup
  stage: build
  variables:
    VLX_NUM_BUILD_JOBS: "6"
  script:
    - python3 -m pip install .[qmmm]

monkey:unit_tests:
  extends: .monkey:setup
  stage: test
  needs: ["monkey:build"]
  script:
    - ./build/bin/UnitTestVeloxChem.x

monkey:python_tests:
  extends: .monkey:setup
  stage: test
  needs: ["monkey:pip_install"]
  script:
    - python3 -m pytest -v --cov=veloxchem --pyargs veloxchem
    - mpiexec -n 2 python3 -m pytest -v --pyargs veloxchem -m "solvers"
    - echo y | python3 -m pip uninstall cppe
