#
#                           VELOXCHEM 1.0-RC2
#         ----------------------------------------------------
#                     An Electronic Structure Code
#
#  Copyright © 2018-2021 by VeloxChem developers. All rights reserved.
#  Contact: https://veloxchem.org/contact
#
#  SPDX-License-Identifier: LGPL-3.0-or-later
#
#  This file is part of VeloxChem.
#
#  VeloxChem is free software: you can redistribute it and/or modify it under
#  the terms of the GNU Lesser General Public License as published by the Free
#  Software Foundation, either version 3 of the License, or (at your option)
#  any later version.
#
#  VeloxChem is distributed in the hope that it will be useful, but WITHOUT
#  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#  FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
#  License for more details.
#
#  You should have received a copy of the GNU Lesser General Public License
#  along with VeloxChem. If not, see <https://www.gnu.org/licenses/>.

stages:
  - deploy

.monkey:setup:
  tags:
    - vlx-docker
  image: ghcr.io/enccs/meta-vlx/vlx-ci_intel:sha-4672d65
  variables:
    OMP_NUM_THREADS: "6"
  before_script:
    - uname -a
    - free -m
    - df -h
    - ulimit -a
    - ulimit -s unlimited
    - lscpu | egrep 'Thread|Core|Socket|^CPU\('
    - python -V
    - mpiicc --version
    - mpiicpc --version
    - python -m venv --clear venv
    - source venv/bin/activate
    - python -m pip install --upgrade pip setuptools wheel

#monkey:build:
#  extends: .monkey:setup
#  stage: build
#  variables:
#    GTESTLIB: "/usr/lib/x86_64-linux-gnu"
#  script:
#    - python -m pip install numpy pybind11 mpi4py --no-binary=mpi4py
#    - python config/generate_setup.py
#    - make -j 6 -C src release
#    - make -j 6 -C unit_tests release
#  artifacts:
#    paths:
#      - build
#    expire_in: 2 hours
#
#monkey:unit_tests:
#  extends: .monkey:setup
#  stage: test
#  needs: ["monkey:build"]
#  script:
#    - ./build/bin/UnitTestVeloxChem.x
#
#monkey:python_tests:
#  extends: .monkey:setup
#  stage: test
#  variables:
#    VLX_NUM_BUILD_JOBS: "6"
#  script:
#    - python -m pip install mpi4py --no-binary=mpi4py
#    - CC=gcc CXX=g++ python -m pip install cppe MDAnalysis
#    - python -m pip install .[test,qmmm]
#    - python -c "import veloxchem; print(veloxchem.__version__)"
#    - mpiexec -n 2 python -m pytest -v --pyargs veloxchem -m "solvers"
#    - python -m pytest -v --cov=veloxchem --pyargs veloxchem

monkey:deploy:
  tags:
    - vlx-docker
  image: ghcr.io/enccs/meta-vlx/vlx-ci_intel:sha-5e6dcd2
  stage: deploy
  variables:
    TARBALL: "veloxchem.tar.bz2"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_COMMIT_TITLE =~ /\[conda-build\]/i'
  script:
    # prepare tar.bz2 archive
    - git archive
        --format=tar
        --prefix="veloxchem/"
        "$CI_COMMIT_SHA" | bzip2 > "$TARBALL"
    - tar tf "$TARBALL"
    # trigger deployment
    - python .gitlab/trigger.py
        --tarball "$TARBALL"
        --url "$CI_API_V4_URL/projects/$CI_PROJECT_ID/jobs/$CI_JOB_ID/artifacts/$TARBALL"
  artifacts:
    paths:
      - "$TARBALL"
    expire_in: 1 week

#include:
#  local: '.gitlab/windows-ci.yml'
