#
#                             VELOXCHEM
#      ---------------------------------------------------
#                     An Electronic Structure Code
#
#  Copyright © 2019 by VeloxChem developers. All rights reserved.
#  Contact: Zilvinas Rinkevicius (rinkevic@kth.se), KTH, Sweden.

before_script:
  - source /opt/intel/bin/compilervars.sh intel64
  - export PATH=/usr/local/cuda/bin:$PATH
  - export DYLD_LIBRARY_PATH=/usr/local/cuda/lib:$DYLD_LIBRARY_PATH
  - export PATH=/home/xinli/software/anaconda3/bin:$PATH
  - export OMP_NUM_THREADS=6

after_script:
  - echo "Done!"

stages:
  - build
  - test

velxochem_build:
  tags:
    - vlx-test
  stage: build
  script:
    - cp config/Setup.Ubuntu.Intel src/Makefile.setup
    - make -j 6 -C src release && make -j 6 -C unit_tests release

veloxchem_test:
  tags:
    - vlx-test
  stage: test
  script:
    - cp config/Setup.Ubuntu.Intel src/Makefile.setup
    - make -j 6 -C src release && make -j 6 -C unit_tests release
    - export PYTHONPATH=$(pwd)/build/python:$PYTHONPATH
    - ./build/bin/UnitTestVeloxChemMP.x && python3 -m pytest -v --cov=veloxchem
