#
#                             VELOXCHEM
#      ---------------------------------------------------
#                     An Electronic Structure Code
#
#  Copyright © 2019 by VeloxChem developers. All rights reserved.
#  Contact: Zilvinas Rinkevicius (rinkevic@kth.se), KTH, Sweden.

before_script:
  - . /opt/intel/bin/compilervars.sh intel64
  - export PATH=/opt/intel/intelpython3/bin:$PATH
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/intel/intelpython3/lib
  - export OMP_NUM_THREADS=10
  - export PYTHONPATH=$PYTHONPATH:/home/xinli/software/cppe/build/stage/lib

after_script:
  - echo "Done!"

stages:
  - build
  - test

velxochem_build:
  tags:
    - vlx-test
  stage: build
  script:
    - python3 config/generate_setup.py
    - make -j 10 -C src release && make -j 10 -C unit_tests release

veloxchem_test:
  tags:
    - vlx-test
  stage: test
  script:
    - python3 config/generate_setup.py
    - make -j 10 -C src release && make -j 10 -C unit_tests release
    - export PYTHONPATH=$(pwd)/build/python:$PYTHONPATH
    - ./build/bin/UnitTestVeloxChemMP.x && python3 -m pytest -v --cov=veloxchem
