#
#                             VELOXCHEM
#      ---------------------------------------------------
#                     An Electronic Structure Code
#
#  Copyright © 2019 by VeloxChem developers. All rights reserved.
#  Contact: Zilvinas Rinkevicius (rinkevic@kth.se), KTH, Sweden.

before_script:
  - export PATH=/usr/lib/binutils-2.26/bin:$PATH
  - export PATH=/home/xinli/software/anaconda3/bin:$PATH
  - export PATH=/home/xinli/software/openmpi/4.0.1/bin:$PATH
  - export LD_LIBRARY_PATH=/home/xinli/software/openmpi/4.0.1/lib:$LD_LIBRARY_PATH
  - export PYTHONPATH=/home/xinli/software/cppe/build/stage/lib:$PYTHONPATH
  - export OMP_NUM_THREADS=6

after_script:
  - echo "Done!"

stages:
  - build
  - test

velxochem_build:
  tags:
    - vlx-test
  stage: build
  script:
    - cp config/Setup.Monkey src/Makefile.setup
    - make -j 6 -C src release && make -j 6 -C unit_tests release

veloxchem_test:
  tags:
    - vlx-test
  stage: test
  script:
    - cp config/Setup.Monkey src/Makefile.setup
    - make -j 6 -C src release && make -j 6 -C unit_tests release
    - export PYTHONPATH=$(pwd)/build/python:$PYTHONPATH
    - ./build/bin/UnitTestVeloxChemMP.x && python3 -m pytest -v --cov=veloxchem
