#
#                           VELOXCHEM 1.0-RC
#      ---------------------------------------------------
#                     An Electronic Structure Code
#
#  Copyright © 2018-2020 by VeloxChem developers. All rights reserved.
#  Contact: https://veloxchem.org/contact

before_script:
  - set +e && source /opt/intel/bin/compilervars.sh intel64 && set -e
  - export PATH=/opt/intel/intelpython3/bin:$PATH
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/intel/intelpython3/lib
  - export OMP_NUM_THREADS=6
  - export GTESTROOT=/home/xinli/software/googletest/googletest
  - export GTESTLIB=/home/xinli/software/googletest/googletest/lib/libgtest.a
  - export MPICC=$I_MPI_ROOT/intel64/mpi/mpiicc

after_script:
  - echo "Done!"

stages:
  - build
  - test

velxochem_build:
  tags:
    - vlx-test
  stage: build
  script:
    - python3 config/generate_setup.py
    - make -j 6 -C src release && make -j 6 -C unit_tests release

veloxchem_test:
  tags:
    - vlx-test
  stage: test
  script:
    - python3.6 -m venv --without-pip venv
    - source venv/bin/activate
    - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    - python3 get-pip.py
    - pip install -r requirements-dev.txt
    - pip install pybind11
    - python3 -m pytest -v --cov=veloxchem python_tests/
    - python3 config/generate_setup.py
    - make -C unit_tests -j -s && ./build/bin/UnitTestVeloxChem.x 
