#
#                      V.E.L.O.X. C.H.E.M. MP
#      ---------------------------------------------------
#           An Electronic Structure Code for Nanoscale
#
#  Created by Zilvinas Rinkevicius (rinkevic@kth.se), KTH, Sweden.
#  Copyright © 2018 by Velox Chem MP developers. All rights reserved.

before_script:
  - source /opt/intel/bin/compilervars.sh intel64
  - export PATH=/usr/local/cuda/bin:$PATH
  - export DYLD_LIBRARY_PATH=/usr/local/cuda/lib:$DYLD_LIBRARY_PATH
  - export PATH=/home/xinli/software/python/bin:$PATH
  - export PYTHONPATH=/home/xinli/software/python/lib/python3.6/site-packages:$PYTHONPATH
  - export PYTHONPATH=/home/xinli/gitlab/VeloxChemMP/bin:$PYTHONPATH
  - export LD_LIBRARY_PATH=/home/xinli/software/python/lib:$LD_LIBRARY_PATH
  - export LD_LIBRARY_PATH=/home/xinli/software/boost/lib:$LD_LIBRARY_PATH

after_script:
  - echo "Done..."

stages: 
  - build
  - test 

build_veloxchem:
  tags: 
   - vlx-test
  stage: build
  script:
    - cd src 
    - cp ../config/Setup.Monkey Makefile.setup 
    - make -j 6 release 
   
build_unit_test:
  tags: 
    - vlx-test
  stage: build
  script: 
    - cd src
    - cp ../config/Setup.Monkey Makefile.setup
    - cd ../unit_tests/
    - make -j 6 release 

build_veloxchem_python3:
  tags: 
   - vlx-test
  stage: build
  script:
    - cd src 
    - cp ../config/Setup.Monkey.Python Makefile.setup 
    - make -j 6 release 

run_unit_test: 
  tags: 
    - vlx-test
  stage: test
  script: 
    - cd src
    - cp ../config/Setup.Monkey Makefile.setup
    - cd ../unit_tests/
    - make -j 6 release
    - cd ../bin/
    - ./UnitTestVeloxChemMP.x

run_test_python3: 
  tags: 
    - vlx-test
  stage: test
  script: 
    - cd src
    - cp ../config/Setup.Monkey.Python Makefile.setup
    - make -j 6 release
    - cd ../integration_tests/
    - python3 test.py
