#
#                             VELOXCHEM
#      ---------------------------------------------------
#                     An Electronic Structure Code
#
#  Copyright © 2019 by VeloxChem developers. All rights reserved.
#  Contact: Zilvinas Rinkevicius (rinkevic@kth.se), KTH, Sweden.

before_script:
  - source /opt/intel/bin/compilervars.sh intel64
  - export PATH=/home/xinli/software/anaconda3/bin:$PATH
  - export PYBIND11ROOT=/home/xinli/software/pybind11
  - export GTESTROOT=/home/xinli/software/googletest/googletest
  - export GTESTLIB=/home/xinli/software/googletest/googletest/lib/libgtest.a
  - export OMP_NUM_THREADS=6
  - export PYTHONPATH=/home/xinli/software/cppe/build/stage/lib:$PYTHONPATH
  - export LD_LIBRARY_PATH=/home/xinli/compiler/gcc/5.3.0/lib64:$LD_LIBRARY_PATH
  - export PATH=/usr/lib/binutils-2.26/bin:$PATH

after_script:
  - echo "Done!"

stages:
  - build
  - test

velxochem_build:
  tags:
    - vlx-test
  stage: build
  script:
    - cp config/Setup.Monkey src/Makefile.setup
    - make -j 6 -C src release
    - python3 config/generate_setup.py
    - make -j 6 -C unit_tests release

veloxchem_test:
  tags:
    - vlx-test
  stage: test
  script:
    - cp config/Setup.Monkey src/Makefile.setup
    - make -j 6 -C src release
    - python3 config/generate_setup.py
    - make -j 6 -C unit_tests release
    - export PYTHONPATH=$(pwd)/build/python:$PYTHONPATH
    - ./build/bin/UnitTestVeloxChemMP.x && python3 -m pytest -v --cov=veloxchem
