[build-system]
# additional build requirements, e.g. numpy and mpi4py, come from setup.py
# through the PEP 517 interface
requires = [
  "setuptools>=42", 
  "wheel",
  "pybind11>=2.6",
]
build-backend = "setuptools.build_meta"
