name: ci workflow

on:
  push:
    branches:
      - simd_master_test

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/veloxchem/meta-vlx/vlx-ci_intel:sha-c8613aa

    env:
      VLX_NUM_BUILD_JOBS: 4

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup env
        run: |
          echo "=== System Info ==="
          uname -a
          free -m
          df -h
          ulimit -a
          ulimit -s unlimited
          lscpu | egrep 'Thread|Core|Socket|^CPU\('
          echo "=== Intel OneAPI ==="
          . /opt/intel/oneapi/setvars.sh intel64
          mpiicc -cc=icx --version
          mpiicpc -cxx=icpx --version
          echo "=== Python ==="
          which python
          python -V
          echo "=== Python venv ==="
          python -m venv --clear venv
          . venv/bin/activate
          which python
          python -V
          echo "=== Python dependencies ==="
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install numpy pybind11[global]
          CC=icx MPICC="mpiicc -cc=icx" python -m pip install mpi4py --no-binary=mpi4py
          echo "=== CMake ==="
          cmake -S.  -Bbuild -GNinja -DCMAKE_CXX_COMPILER=mpiicpc -DCMAKE_CXX_FLAGS="-cxx=icpx" -DVLX_LA_VENDOR=MKL
          cmake --build build --parallel "$VLX_NUM_BUILD_JOBS" --target veloxchemlib -- -d stats
