name: build

on:
  push:
    branches:
      - simd_master_test

jobs:
  vlx_ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    container:
      image: ghcr.io/veloxchem/meta-vlx/vlx-ci_gnu:sha-c8613aa

    env:
      VLX_NUM_BUILD_JOBS: 4

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: build and test
        run: |
          echo "=== System Info ==="
          uname -a
          free -m
          df -h
          ulimit -a
          ulimit -s unlimited
          lscpu | egrep 'Thread|Core|Socket|^CPU\('
          echo "=== GNU Compiler ==="
          #mpicc --version
          #mpicc -show
          #mpicxx --version
          #mpicxx -show
          gcc --version
          g++ --version
          echo "=== Python ==="
          which python
          python -V
          echo "=== Python venv ==="
          python -m venv --clear venv
          source venv/bin/activate
          which python
          python -V
          echo "=== Python dependencies ==="
          python -m pip install --upgrade pip setuptools wheel
          CC=gcc MPICC=mpicc python -m pip install mpi4py --no-binary=mpi4py
          CC=gcc CXX=g++ python -m pip install cppe MDAnalysis
          echo "=== VeloxChem build ==="
          SKBUILD_CONFIGURE_OPTIONS="-DVLX_LA_VENDOR=MKL -DCMAKE_CXX_COMPILER=g++" \
            python -m pip install -v .[test,qmmm]
          echo "=== VeloxChem test ==="
          python -c "import veloxchem; print(veloxchem.__version__)"
          OMP_NUM_THREADS=2 mpiexec -n 2 python -m pytest --capture=no --log-cli-level=INFO --pyargs veloxchem -m "solvers"
          OMP_NUM_THREADS=4 python -m pytest --cov=veloxchem --capture=no --log-cli-level=INFO --pyargs veloxchem -k "not test_h2o_dimer_tzvp_comp_electronic_grad"
