name: VeloxChem CI workflow

on:
  push:
    branches:
      - simd_master_test

jobs:
  vlx_ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    container:
      image: ghcr.io/veloxchem/meta-vlx/vlx-ci_intel:sha-c8613aa

    env:
      VLX_NUM_BUILD_JOBS: 4

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: build and test
        run: |
          echo "=== System Info ==="
          uname -a
          free -m
          df -h
          ulimit -a
          ulimit -s unlimited
          lscpu | egrep 'Thread|Core|Socket|^CPU\('
          echo "=== Intel OneAPI ==="
          source /opt/intel/oneapi/setvars.sh
          mpiicc -cc=icx --version
          mpiicpc -cxx=icpx --version
          echo "=== Python ==="
          which python
          python -V
          echo "=== Python venv ==="
          python -m venv --clear venv
          source venv/bin/activate
          which python
          python -V
          echo "=== Python dependencies ==="
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install numpy pybind11[global]
          CC=icx MPICC="mpiicc -cc=icx" python -m pip install mpi4py --no-binary=mpi4py
          CC=gcc CXX=g++ python -m pip install cppe MDAnalysis
          echo "=== VeloxChem ==="
          SKBUILD_CONFIGURE_OPTIONS="-DVLX_LA_VENDOR=MKL -DCMAKE_CXX_COMPILER=mpiicpc -DCMAKE_CXX_FLAGS=\"-cxx=icpx\"" \
            python -m pip install -v .[test,qmmm]
